
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 3;
  public static final int SEMIC = 6;
  public static final int EQ = 9;
  public static final int EOF = 0;
  public static final int NUMERO = 7;
  public static final int RBRACKET = 5;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMANDO = 2;
  public static final int LBRACKET = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMANDO",
  "COMA",
  "LBRACKET",
  "RBRACKET",
  "SEMIC",
  "NUMERO",
  "ID",
  "EQ"
  };
}

